/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaxiRouteImport } from './routes/taxi'
import { Route as StaysRouteImport } from './routes/stays'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaysIdRouteImport } from './routes/stays_.$id'
import { Route as MyBookingsReferenceRouteImport } from './routes/my-bookings_.$reference'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminTaxiRouteImport } from './routes/_authenticated/admin.taxi'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin.enquiries'
import { Route as AuthenticatedAdminDriversRouteImport } from './routes/_authenticated/admin.drivers'
import { Route as AuthenticatedAdminCalendarRouteImport } from './routes/_authenticated/admin.calendar'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'
import { Route as AuthenticatedAdminApartmentsRouteImport } from './routes/_authenticated/admin.apartments'
import { Route as AuthenticatedAdminTaxiIdRouteImport } from './routes/_authenticated/admin.taxi_.$id'
import { Route as AuthenticatedAdminDriversIdRouteImport } from './routes/_authenticated/admin.drivers_.$id'

const TaxiRoute = TaxiRouteImport.update({
  id: '/taxi',
  path: '/taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysRoute = StaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysIdRoute = StaysIdRouteImport.update({
  id: '/stays_/$id',
  path: '/stays/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsReferenceRoute = MyBookingsReferenceRouteImport.update({
  id: '/my-bookings_/$reference',
  path: '/my-bookings/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTaxiRoute = AuthenticatedAdminTaxiRouteImport.update({
  id: '/taxi',
  path: '/taxi',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDriversRoute =
  AuthenticatedAdminDriversRouteImport.update({
    id: '/drivers',
    path: '/drivers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCalendarRoute =
  AuthenticatedAdminCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApartmentsRoute =
  AuthenticatedAdminApartmentsRouteImport.update({
    id: '/apartments',
    path: '/apartments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTaxiIdRoute =
  AuthenticatedAdminTaxiIdRouteImport.update({
    id: '/taxi_/$id',
    path: '/taxi/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDriversIdRoute =
  AuthenticatedAdminDriversIdRouteImport.update({
    id: '/drivers_/$id',
    path: '/drivers/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amenities': typeof AmenitiesRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/driver': typeof DriverRoute
  '/my-bookings': typeof MyBookingsRoute
  '/stays': typeof StaysRoute
  '/taxi': typeof TaxiRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/my-bookings/$reference': typeof MyBookingsReferenceRoute
  '/stays/$id': typeof StaysIdRoute
  '/admin/apartments': typeof AuthenticatedAdminApartmentsRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/taxi': typeof AuthenticatedAdminTaxiRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/drivers/$id': typeof AuthenticatedAdminDriversIdRoute
  '/admin/taxi/$id': typeof AuthenticatedAdminTaxiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amenities': typeof AmenitiesRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/driver': typeof DriverRoute
  '/my-bookings': typeof MyBookingsRoute
  '/stays': typeof StaysRoute
  '/taxi': typeof TaxiRoute
  '/my-bookings/$reference': typeof MyBookingsReferenceRoute
  '/stays/$id': typeof StaysIdRoute
  '/admin/apartments': typeof AuthenticatedAdminApartmentsRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/taxi': typeof AuthenticatedAdminTaxiRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/drivers/$id': typeof AuthenticatedAdminDriversIdRoute
  '/admin/taxi/$id': typeof AuthenticatedAdminTaxiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/amenities': typeof AmenitiesRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/driver': typeof DriverRoute
  '/my-bookings': typeof MyBookingsRoute
  '/stays': typeof StaysRoute
  '/taxi': typeof TaxiRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/my-bookings_/$reference': typeof MyBookingsReferenceRoute
  '/stays_/$id': typeof StaysIdRoute
  '/_authenticated/admin/apartments': typeof AuthenticatedAdminApartmentsRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/_authenticated/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/taxi': typeof AuthenticatedAdminTaxiRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/drivers_/$id': typeof AuthenticatedAdminDriversIdRoute
  '/_authenticated/admin/taxi_/$id': typeof AuthenticatedAdminTaxiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amenities'
    | '/auth'
    | '/book'
    | '/contact'
    | '/driver'
    | '/my-bookings'
    | '/stays'
    | '/taxi'
    | '/admin'
    | '/my-bookings/$reference'
    | '/stays/$id'
    | '/admin/apartments'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/drivers'
    | '/admin/enquiries'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/taxi'
    | '/admin/'
    | '/admin/drivers/$id'
    | '/admin/taxi/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amenities'
    | '/auth'
    | '/book'
    | '/contact'
    | '/driver'
    | '/my-bookings'
    | '/stays'
    | '/taxi'
    | '/my-bookings/$reference'
    | '/stays/$id'
    | '/admin/apartments'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/drivers'
    | '/admin/enquiries'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/taxi'
    | '/admin'
    | '/admin/drivers/$id'
    | '/admin/taxi/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/amenities'
    | '/auth'
    | '/book'
    | '/contact'
    | '/driver'
    | '/my-bookings'
    | '/stays'
    | '/taxi'
    | '/_authenticated/admin'
    | '/my-bookings_/$reference'
    | '/stays_/$id'
    | '/_authenticated/admin/apartments'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/calendar'
    | '/_authenticated/admin/drivers'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/taxi'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/drivers_/$id'
    | '/_authenticated/admin/taxi_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AmenitiesRoute: typeof AmenitiesRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DriverRoute: typeof DriverRoute
  MyBookingsRoute: typeof MyBookingsRoute
  StaysRoute: typeof StaysRoute
  TaxiRoute: typeof TaxiRoute
  MyBookingsReferenceRoute: typeof MyBookingsReferenceRoute
  StaysIdRoute: typeof StaysIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/taxi': {
      id: '/taxi'
      path: '/taxi'
      fullPath: '/taxi'
      preLoaderRoute: typeof TaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays': {
      id: '/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof StaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays_/$id': {
      id: '/stays_/$id'
      path: '/stays/$id'
      fullPath: '/stays/$id'
      preLoaderRoute: typeof StaysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings_/$reference': {
      id: '/my-bookings_/$reference'
      path: '/my-bookings/$reference'
      fullPath: '/my-bookings/$reference'
      preLoaderRoute: typeof MyBookingsReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/taxi': {
      id: '/_authenticated/admin/taxi'
      path: '/taxi'
      fullPath: '/admin/taxi'
      preLoaderRoute: typeof AuthenticatedAdminTaxiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/drivers': {
      id: '/_authenticated/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AuthenticatedAdminDriversRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calendar': {
      id: '/_authenticated/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AuthenticatedAdminCalendarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/apartments': {
      id: '/_authenticated/admin/apartments'
      path: '/apartments'
      fullPath: '/admin/apartments'
      preLoaderRoute: typeof AuthenticatedAdminApartmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/taxi_/$id': {
      id: '/_authenticated/admin/taxi_/$id'
      path: '/taxi/$id'
      fullPath: '/admin/taxi/$id'
      preLoaderRoute: typeof AuthenticatedAdminTaxiIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/drivers_/$id': {
      id: '/_authenticated/admin/drivers_/$id'
      path: '/drivers/$id'
      fullPath: '/admin/drivers/$id'
      preLoaderRoute: typeof AuthenticatedAdminDriversIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApartmentsRoute: typeof AuthenticatedAdminApartmentsRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminCalendarRoute: typeof AuthenticatedAdminCalendarRoute
  AuthenticatedAdminDriversRoute: typeof AuthenticatedAdminDriversRoute
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTaxiRoute: typeof AuthenticatedAdminTaxiRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminDriversIdRoute: typeof AuthenticatedAdminDriversIdRoute
  AuthenticatedAdminTaxiIdRoute: typeof AuthenticatedAdminTaxiIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApartmentsRoute: AuthenticatedAdminApartmentsRoute,
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminCalendarRoute: AuthenticatedAdminCalendarRoute,
  AuthenticatedAdminDriversRoute: AuthenticatedAdminDriversRoute,
  AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTaxiRoute: AuthenticatedAdminTaxiRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminDriversIdRoute: AuthenticatedAdminDriversIdRoute,
  AuthenticatedAdminTaxiIdRoute: AuthenticatedAdminTaxiIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AmenitiesRoute: AmenitiesRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DriverRoute: DriverRoute,
  MyBookingsRoute: MyBookingsRoute,
  StaysRoute: StaysRoute,
  TaxiRoute: TaxiRoute,
  MyBookingsReferenceRoute: MyBookingsReferenceRoute,
  StaysIdRoute: StaysIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
